### ISSUE TITLE
Pagination for Repository Results

### ISSUE THREAD

**Issue by jaiyankargupta** [jaiyankargupta/GitExplorer#2]
Issue: Currently, GitExplorer may only display a limited number of repositories, possibly leaving out important ones if the search criteria return too many results.

Suggested Improvement: Add pagination or infinite scroll to allow users to browse through a larger set of repositories.

Solution: Implement pagination controls or an infinite scroll feature to load more repositories dynamically.

**Comment by AnhChienVu** [comment]
Hi @jaiyankargupta, I want to work on this issue, would you mind if you can assign me to this?

**Comment by jaiyankargupta** [comment]
@AnhChienVu done ✅

**Comment by AnhChienVu** [comment]
As I researched, GitHub API only allows us to fetch up to 1000 results for the sake of user's experience. So I will only set the maximum page as 100, even the fetched data shows tons of results.

**Comment by jaiyankargupta** [comment]
@AnhChienVu okay

**Comment by AnhChienVu** [comment]
I made a PR for this issue already
