### ISSUE TITLE
Authentication and Personalization

### ISSUE THREAD

**Issue by jaiyankargupta** [jaiyankargupta/GitExplorer#6]
Issue: The application does not currently support GitHub authentication, which limits the ability to offer personalized experiences like favoriting repositories or following topics.

Suggested Improvement: Add GitHub OAuth authentication to allow users to log in, access their favorite repositories, and save preferences.

Solution: Implement GitHub OAuth, enabling users to log in and personalize their search experience, including bookmarking or saving favorite repositories.

**Comment by AnhChienVu** [comment]
Hi @jaiyankargupta, I want to give it a try. So as I assumed that we need to create a backend to integrate with the current front-end. I'm gonna implement it by using express framework. Do you think that it is fine? And if you don't mind, could you assign me?

**Comment by jaiyankargupta** [comment]
@AnhChienVu okay, assigned

**Comment by AnhChienVu** [comment]
How do you think if I create a button to access all starred repos for an authenticated user, then this user can search repos then add to favorite repos (starred repos). Is it what you want to implement, isn't it?

**Comment by jaiyankargupta** [comment]
i think, this is great idea to create a button to access all starred repo. you can implement this.
