### ISSUE TITLE
 Dark Mode for Better User Experience

### ISSUE THREAD

**Issue by jaiyankargupta** [jaiyankargupta/GitExplorer#7]
Issue: The current design may lack a dark mode, which can be a preferred option for many developers, especially during late-night browsing.

Suggested Improvement: Introduce a dark mode toggle to improve user comfort and accessibility in low-light environments.

Solution: Add a switch in the user interface to enable dark mode, applying a dark color scheme to the entire application.

**Comment by moudgalya1223** [comment]
can We work together to close this

**Comment by jaiyankargupta** [comment]
@moudgalya1223 yes

**Comment by moudgalya1223** [comment]
hello @jaiyankargupta  can you help me with the url in the prdouction please

**Comment by moudgalya1223** [comment]
hello @jaiyankargupta  made the changes and pushed , working good in local Hope it resolves the issue thanks

**Comment by RashmitTopG** [comment]
I also made a change and pushed
